### PR TITLE
Vnext/dotnet8 upgrade

### LINKED ISSUE #401: [Feature Contribution]: Upgrade .NET version to .NET 8
### What happened?

.NET 8 that is the next LTS version of .NET is planned to be release Nov. 2023.  Carbon Aware SDK should be upgraded to .NET 8 because using the latest LTS is good practice, generally. 

FYI, .NET 8 contains important improvements to implement #400. 
* https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#metrics
* https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#imeterfactory-interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### PR DESCRIPTION
**Pull request by YaSuenag**
# Pull Request

#401

## Summary

* Migrate to .NET 8
* Introduce cache feature for emission data
* Introduce Prometheus exporter in WebAPI

Big thanks to @tiwatsuka

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No

## Is this a breaking change?

No

This PR Closes #401

### CODE REVIEW

**Comment by YaSuenag** [comment]
This PR seems to conflict in casdk-docs/docs/overview/overview.md . I want to fix, but I haven't write permission on GSF repo, so I cannot fix. Can you help? @vaughanknight @danuw 

I think we should copy casdk-docs/docs/overview/overview.md in dev branch into this PR without any changes - it means we can ignore changes in overview.md in this PR.

**Comment by vaughanknight** [comment]
@danuw to resolve the conflict, as discussed on call ready to merge

**Comment by danuw** [comment]
@YaSuenag we have removed the `overview.md` - would you be able to ensure any content that needs to be ported over has moved to `enablement.md` and then we delete from that branch (I saw there is your video at the bottom on helm I am not sure we have elsewhere, could you move that - create a new PR if needed - please?)

**Comment by YaSuenag** [comment]
I cannot modify this branch because it is located at GSF repo - I do not have write permission.  
So I re-open another PR from my repo: #493, I'd like to continue this work in that PR.

>  would you be able to ensure any content that needs to be ported over has moved to enablement.md and then we delete from that branch (I saw there is your video at the bottom on helm I am not sure we have elsewhere, could you move that 

All contents of previous overview.md (includes my video to instruct WebAPI installation with Helm) is available in enablement.md, so I think we can remove overview.md now. But I think it is an another issue. So I will open PR after this.

**Pull request closed without merging**
