### PR TITLE
211/improve diagnostics tracing

### LINKED ISSUE #220: [Feature Contribution]: Improve code related to diagnostics/tracing.
### What happened?

As a carbon aware developer, I can access consistent telemetry libraries and utilities so that I can plumb through telemetry signals throughout the project. 

The current code base has extremely verbose tracing with new traces created in multiple tiers of the app and for all routes. Ideally, activities should be tracked at an application boundary i.e at entry and exit points. The goal is to clean up existing tracing code and create a consistent utility to track the telemetry signals. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### PR DESCRIPTION
**Pull request by pritipath**
Issue Number: #220

## Summary
 Improve code related to diagnostics/tracing

## Changes

- List of comprehensive changes

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.

## Is this a breaking change?
If yes, what workflow does this break? 

## Anything else?
Other comments, collaborators, etc.
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords

This PR Closes #220

### CODE REVIEW

**Review by JenMadiedo — APPROVED** [review]
All looks good to me, thanks for all the cleanup!

For my own understanding, we essentially moved aware from the activities and instead instantiate tracers on the WebApi and CLI that can track logs?

**Comment by pritipath** [comment]
> All looks good to me, thanks for all the cleanup!
> 
> For my own understanding, we essentially moved aware from the activities and instead instantiate tracers on the WebApi and CLI that can track logs?

Yes. We decided to track 2 activities - one at the entry point in our app and second when we exit our app to make a call to the data source. This helped reduce the noise in our tracing considerably.

**Review by bderusha — APPROVED** [review]

**Review by juzuluag — COMMENTED** [review]
This looks great!!. Finally this big cleanup. But I have a question: Shouldn't be the OpenTelemetry handled like it was done for `AppInsights`? See `AddMonitoringAndTelemetry`

**Comment by bderusha** [comment]
> This looks great!!. Finally this big cleanup. But I have a question: Shouldn't be the OpenTelemetry handled like it was done for `AppInsights`? See `AddMonitoringAndTelemetry`

@juzuluag This is slightly different IMO.  For AppInsights to work you must configure your particular connection string and we wrote a decent amount of custom code to manage that.  OpenTelemetry is only creating the traces locally, not sending them anywhere specific (beyond the console), so there is no custom logic beyond telling the app to use the out-of-the-box package. We have tended to put such direct usage right into Program.cs, so this felt reasonable.

All that said, there is little harm in moving it to an extension class if it improves the readability of the Program file.  I would leave that choice to the discretion of the implementer

**Comment by juzuluag** [comment]
> > This looks great!!. Finally this big cleanup. But I have a question: Shouldn't be the OpenTelemetry handled like it was done for `AppInsights`? See `AddMonitoringAndTelemetry`
> 
> @juzuluag This is slightly different IMO. For AppInsights to work you must configure your particular connection string and we wrote a decent amount of custom code to manage that. OpenTelemetry is only creating the traces locally, not sending them anywhere specific (beyond the console), so there is no custom logic beyond telling the app to use the out-of-the-box package. We have tended to put such direct usage right into Program.cs, so this felt reasonable.
> 
> All that said, there is little harm in moving it to an extension class if it improves the readability of the Program file. I would leave that choice to the discretion of the implementer.
> 
> It would probably be beneficial to add some documentation linking to the OpenTelemetry docs on how to configure it to send the traces somewhere more useful in a production environment (like zipkin, jaeger, etc.)

@bderusha, thanks for the explanation. Agree that adding some `HowTo` to configure different consumers would help to integrate with OT. Is the intent to have OT enabled by default? Or should it be enabled based on configuration options? (i.e similar to what AppInsights integration does)

**Comment by bderusha** [comment]
> > > This looks great!!. Finally this big cleanup. But I have a question: Shouldn't be the OpenTelemetry handled like it was done for `AppInsights`? See `AddMonitoringAndTelemetry`
> > 
> > 
> > @juzuluag This is slightly different IMO. For AppInsights to work you must configure your particular connection string and we wrote a decent amount of custom code to manage that. OpenTelemetry is only creating the traces locally, not sending them anywhere specific (beyond the console), so there is no custom logic beyond telling the app to use the out-of-the-box package. We have tended to put such direct usage right into Program.cs, so this felt reasonable.
> > All that said, there is little harm in moving it to an extension class if it improves the readability of the Program file. I would leave that choice to the discretion of the implementer.
> > It would probably be beneficial to add some documentation linking to the OpenTelemetry docs on how to configure it to send the traces somewhere more useful in a production environment (like zipkin, jaeger, etc.)
> 
> @bderusha, thanks for the explanation. Agree that adding some `HowTo` to configure different consumers would help to integrate with OT. Is the intent to have OT enabled by default? Or should it be enabled based on configuration options? (i.e similar to what AppInsights integration does)

The intent is that it is enabled (creating traces) but dormant (not sending them anywhere) by default.  This is because the configuration to send the traces is generic enough that the operator will very likely need to augment `Program.cs` in some way no matter what to send the traces.

**Comment by vaughanknight** [comment]
@bderusha do you know if this one is ready for review?  Just following up on some of the older PR's to check they are still going.

Also - I added a tag that is "Ready for review" so you can tag PR's when they are ready (saves me having to check all the chat logs, and also means if you change your mind, the tag can be easily removed.

**Comment by bderusha** [comment]
@vaughanknight Once we resolve the conflicts and add to the documentation this will be ready to go.

Unfortunately, without contributor/write permissions on the project I can't add labels.

**Review by juzuluag — APPROVED** [review]
👍

**Comment by pritipath** [comment]
@vaughanknight @Willmish This PR is ready for GSF review.

**Pull request merged**
