### PR TITLE
Move CarbonAwareParameters to CarbonAware Project

### LINKED ISSUE #284: [Feature Contribution]: Move Carbon Aware Parameters to Carbon Aware Project
### What happened?

The Carbon Aware Parameters are used by the CLI, Web API and the Library so they should be located in the shared CarbonAware project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### PR DESCRIPTION
**Pull request by JenMadiedo**
Issue Number: #284 

## Summary
Move the `CarbonAwareParameters` class to the `CarbonAware` project

## Changes

- Move class to CarbonAware project
- Update references

## Checklist

- [X] Local Tests Passing?
- [X] CICD and Pipeline Tests Passing?
- [X] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [x] This is not a breaking change. If it is, please describe it below.

This PR Closes #284

### CODE REVIEW

**Review by pritipath — APPROVED** [review]
looks good

**Comment by JenMadiedo** [comment]
@vaughanknight this is ready for review

**Review by juzuluag — APPROVED** [review]
👍

**Review by vaughanknight — APPROVED** [review]
Approved, looks good.

**Pull request merged**
