### PR TITLE
ADR for adding option for CLI output to CSV

### PR DESCRIPTION
**Pull request by pritipath**
# Pull Request

## Summary

ADR for providing an option to display CLI output in CSV format

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

If yes, what are the expected API Changes? Please link to an API-Comparison
workflow with the API Diff.

## Is this a breaking change?

If yes, what workflow does this break?

## Anything else?

Other comments, collaborators, etc.

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR Closes #<issue_number>

### CODE REVIEW

**Comment by Willmish** [comment]
Related to #35

**Review by bderusha — COMMENTED** [review]
@pritipath This ADR does a nice job of covering the many different considerations. For a next rev, I would love for it be a bit more opinionated so that someone going to implement such a feature doesn't need to grapple with all of it.

My personal opinion:
- I am usually for not reinventing the wheel and using 3rd Party packages for CSV. But since we only need it for output, unless there is a small/modular package that does only what we need, it may be better to just write it ourself. Definitely depends on some of the answers to my in-line locale question.
- For forecasting my preference would be, having a row for each flattened `ForecastData` value and a column for each flattened `OptimalDataPoint` value. Specifically putting the OptimalDataPoints at the end so that it's easier to programmatically manage them since the first 10 columns will always be the same, and the remaining columns can be parsed as optimal value pairs. EG:

| RequestedAt | Location | ... | ForecastDataTime | ForecastDataRating | OptimalTime_0 | OptimalRating_0 | OptimalTime_1 | OptimalRating_1 |
|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|
| 2023-04-01T00:00:00Z | EastUS | ... | 2023-04-01T01:00:00Z | 123 | 2023-04-01T01:00:00Z | 123 | 2023-04-01T02:00:00Z | 123 | 
| 2023-04-01T00:00:00Z | EastUS | ... | 2023-04-01T02:00:00Z | 123 | 2023-04-01T01:00:00Z | 123 | 2023-04-01T02:00:00Z | 123 | 
| 2023-04-01T00:00:00Z | EastUS | ... | 2023-04-01T03:00:00Z | 456 | 2023-04-01T01:00:00Z | 123 | 2023-04-01T02:00:00Z | 123 |

**Review by Willmish — APPROVED** [review]
Accepting ADR proposal

**Comment by Willmish** [comment]
Reviewed during https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/334 , looking to approve.

**Pull request merged**
