### PR TITLE
feat: CLI should return JSON instead of array of json (for --lowest a…

### PR DESCRIPTION
**Pull request by umairm-tw**
feat: CLI should return JSON instead of array of json (for --lowest argument flag)

### CODE REVIEW

**Comment by vaughanknight** [comment]
I just had a look at the post.  --lowest may return more than one result (for multiple times).  

However it does need to be updated to return json object (with an array inside it) vs a plain array.

**Review by vaughanknight — CHANGES_REQUESTED** [review]
Thanks for jumping on this one.

From what I see here if we are looking at lowest, it returns a single object?   This would be a bug.

Lowest can at times return multiple i.e. multiple times where it is "zero" emissions.  So this should always output an array, which may have 0, 1, or multiple entries.  I'll move discussion to comments.

**Comment by vaughanknight** [comment]
What we would want is a JSON object that returns something like... 
{
   emissionsData: []
}

**Comment by Willmish** [comment]
It should return a JSON object with an array inside -> so it can be parsed

**Comment by Willmish** [comment]
Closing due to inactivity: Issue being addressed in  #94 .

**Pull request closed without merging**
