### PR TITLE
Replace CarbonHack banner with SOGS

### PR DESCRIPTION
**Pull request by holanita**
Hey @vaughanknight Doha suggested we replace the CarbonHack banner with a new one for SOGS. Please check if this looks ok to you. Thanks.

### CODE REVIEW

**Comment by vaughanknight** [comment]
@danuw do you want to merge this with your other changes?  Would be awesome thanks.

**Comment by holanita** [comment]
@danuw I tried to add the image to my commit so it should be there
but if it's not working you can find it in the images folder: images/SOGS_banner1.png

**Comment by holanita** [comment]
and this is the url that it should point to: https://grnsft.org/sogs/survey

**Comment by holanita** [comment]
Closing the PR as the survey will be closed tomorrow.

**Pull request closed without merging**
