### PR TITLE
ADR 0004: Documentation

### PR DESCRIPTION
**Pull request by bderusha**
## Summary
ADR proposal for how to manage current and future documentation.

### CODE REVIEW

**Comment by bderusha** [comment]
@Willmish @vaughanknight My team is looking to clean up a bunch of the documentation around the web API features we contributed recently.  I put together this ADR proposal describing what that could look like.  I would love your feedback on it.

@Willmish It is very much inline with your existing PR #99

**Review by vaughanknight — COMMENTED** [review]
We will review on the call this week with the Carbon Aware SDK GSF team.  We also are doing some documentation update this week for the 1.0 release.

**Comment by danuw** [comment]
Great proposition for the docs - like it for everything to be together.

What caught my attention when I was about to apply those changes was that we would move the readme files from their main projects to the docs folder. I expect I will keep a readme files linking to docs for now.
Would that make sense too?

**Comment by bderusha** [comment]
> Great proposition for the docs - like it for everything to be together.
> 
> What caught my attention when I was about to apply those changes was that we would move the readme files from their main projects to the docs folder. I expect I will keep a readme files linking to docs for now. Would that make sense too?

@danuw Yes, I also think that linking to the appropriate files in the `/docs` directory. I tried to capture that intent in one of the last parts of the proposal [here](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/105/files#diff-97d76a7bb85785bea9a03183e2a55154faa6c28b5bca4b46b9bba125b6dde626R19)

> No documentation shall live outside the `root` or `/docs` directories.  All other `README.md` files must only contain relative links back to the appropriate `/docs` file.

Let me know if you have suggestions for improving the language around it.  Perhaps it would be better to just drop that first sentence and focus on what it should do rather than starting with what it shouldn't.

**Comment by vaughanknight** [comment]
Yep.  Just went back over it and it's covered.  I think we are happy to accept this in the ADRs as we are already making the changes 👍... some before we saw the PR too.  I'll move forward with accepting/ merging the PR.  Thanks all!

**Review by vaughanknight — APPROVED** [review]
The changes are in line with many of the project teams previous discussions with some additional solid thinking.  Happy to move forward with accepting the ADR into the project.

**Comment by vaughanknight** [comment]
I should also state we reviewed on the call and there were no objections.  Thanks again!

**Pull request merged**
