### PR TITLE
Update documentation of Usefulness (adopters.md) 

### LINKED ISSUE #414: Update documentation of Usefulness (adopters.md)
Evidence of project usefulness, through real world use cases in the production environment, including testimonials

### PR DESCRIPTION
**Pull request by tkuramoto33**
# Pull Request

Issue Number: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/414

## Summary

Add docs/adopters.md.

## Changes

Add docs/adopters.md.

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [x] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No.

## Is this a breaking change?

No.

## Anything else?

This PR Closes #414

### CODE REVIEW

**Comment by YaSuenag** [comment]
@Sophietn 
Is this PR enough to  graduation metrics?

**Comment by Sophietn** [comment]
Yes it's enough to Graduate. But are UBS and Vestas the only adopters of the CASDK that we know about? @vaughanknight do you know of any more? I think you mentioned Microsoft and possibly Shell?

**Review by danuw — APPROVED** [review]
LGTM as a start

**Comment by Sophietn** [comment]
@danuw @vaughanknight or @Willmish 
I've reviewed this one from @tkuramoto33. LGTM
Ready for final review and merge thanks

**Review by danuw — APPROVED** [review]

**Pull request merged**
