### PR TITLE
Carbon Aware CLI redesign

### LINKED ISSUE #131: [Feature Contribution]: CLI upgrade to enable access to new features
### What happened?

The current design of the CLI is challenging to extend to take advantage of new features added to the SDK (such as averaging and forecasting).  This contribution will provide an improved experience for users and developers of the CLI by leveraging the `System.CommandLine` package as the framework for implementing current (and future) SDK capabilities.

# Proposed Carbon Aware CLI User Docs

## Build and Install

Build the CLI using the `dotnet publish` command:

```bash
dotnet publish ./src/CarbonAware.CLI/src/CarbonAware.CLI.csproj -c Release -o <your desired installation path>
```

> By default this will build for your host operating system.  To build for a platform other than your host platform you can specify the target runtime like this, using any valid [Runtime ID](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids) (EG `win-x64`, `linux-x64`, `osx-x64`):
>
> ```bash
> dotnet publish .\src\CarbonAware.CLI\src\CarbonAware.CLI.csproj -c Release -r <RuntimeID> --self-contained -o <your desired installation path>
> ```

The default binary name is `caw` (a shorthand for **C**arbon-**AW**are), but this can also be customized at build time if desired.

```sh
dotnet publish .\src\CarbonAware.CLI\src\CarbonAware.CLI.csproj 
 /p:Configuration=Release,AssemblyName=<your desired assembly name>
```

## Using the CLI

To use the CLI for the first time, navigate to your installation directory and run the binary with the `-h` flag to see the help menu.

On Windows: `.\caw.exe -h`
On MacOS/Linux: `.\caw -h`

#### Description

Retrieve emissions data from specified locations and time periods.

#### Usage

`caw emissions [options]`

#### Options

```text
  -l, --location <location> (REQUIRED)  A named location
  -s, --start-time <startTime>          Start time of emissions data
  -e, --end-time <endTime>              End time of emissions data
  -b, --best                            Filter results down to the best (typically lowest) data point.
  -a, --average                         Outputs the weighted average of all data points within the start and end time boundaries.
  -?, -h, --help                        Show help and usage information
```
#### Description

Gets emissions forecast data for given locations.

#### Usage

`caw emissions-forecasts [options]`

#### Options

```text
  -l, --location <location> (REQUIRED)  A list of locations
  --data-start-at <startTime>           Filter out forecasted data points before start at time.
  --data-end-at <endTime>               Filter out forecasted data points after end at time.
  -w, --window-size <INT>                   The estimated duration (in minutes) of the workload being forecasted. Defaults to the duration of a single forecast data point
  --requested-at                        Datetime of a previously generated forecast.  Returns the most current forecast if not provided.
  -?, -h, --help                        Show help and usage information
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### LINKED ISSUE #166: [Bug]: calling the CLI with --version or --help crashes
### Contact Details

andy@bitshaper.co.uk

### What happened?

Using v1.0.0, running the cli with `--version` or `--help` crashes with an unhandled exception.

```
cd src/CarbonAware.CLI/src
dotnet run --version
dotnet run -- --help
```

It does output the version or help text first, so this is not the most important of bugs, so no need to rush to fix!

### client

CLI

### Relevant log output

```shell
bin/Release/net6.0/publish/CarbonAware.CLI --version
CarbonAware.CLI 1.0.0
Unhandled exception. System.ArgumentException: Invalid parameters
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareParameters.AssertNoErrors(Dictionary`2 errors) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareParameters.cs:line 305
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareParameters.Validate() in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareParameters.cs:line 184
   at CarbonAware.Aggregators.CarbonAware.CarbonAwareAggregator.GetEmissionsDataAsync(CarbonAwareParameters parameters) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareAggregator.cs:line 35
   at CarbonAware.CLI.CarbonAwareCLI.GetEmissions() in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.CLI/src/CarbonAwareCLI.cs:line 76
   at CarbonAware.CLI.Program.GetEmissionsAsync(String[] args, ICarbonAwareAggregator aggregator, ILogger`1 logger) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.CLI/src/Program.cs:line 42
   at CarbonAware.CLI.Program.Main(String[] args) in /home/andy/carbon-aware-sdk-1.0.0/src/CarbonAware.CLI/src/Program.cs:line 15
   at CarbonAware.CLI.Program.<Main>(String[] args)
Aborted (core dumped)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #168: [Bug]: CLI does not respect Logging configuration
### Contact Details

andy@bitshaper.co.uk

### What happened?

The CLI currently always has Console debug output enabled, making parsing the JSON difficult as it is printed to the console twice, once as expected, and once in a LogCritical line:

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/d623ea19971324b553dee35d33a0df90d2aa25a7/src/CarbonAware.CLI/src/CarbonAwareCLI.cs#L92-L93

Configuring the `LogLevel` in the `appsettings.json` to `"None"` is ignored and does not work.

I believe this is because the `services.AddLogging` call here:
https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/d623ea19971324b553dee35d33a0df90d2aa25a7/src/CarbonAware.CLI/src/Program.cs#L30

Should read something more like:
```
        services.AddLogging(configure => configure
            .AddConfiguration(config.GetSection("Logging"))
            .AddConsole()
        );
```

### client

CLI

### Relevant log output

```shell
$ dotnet run -l eastus
info: CarbonAware.DataSources.Json.JsonDataSource[0]
      JSON data source getting carbon intensity for locations {"locationType":2,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"eastus","name":"eastus","displayName":"eastus"} for period 10/25/2022 09:27:01 +01:00 to 10/25/2022 09:27:01 +01:00.
info: CarbonAware.DataSources.Json.JsonDataSource[0]
      Reading Json data from carbon-aware-sdk/src/CarbonAware.CLI/src/bin/Debug/net6.0/data-sources/json/test-data-azure-emissions.json
{
  "emissionsData": [
    {
      "Location": "eastus",
      "Time": "2022-10-25T04:45:11+00:00",
      "Rating": 53.0,
      "Duration": "08:00:00"
    }
  ]
}
crit: CarbonAware.CLI.CarbonAwareCLI[0]
      {
        "emissionsData": [
          {
            "Location": "eastus",
            "Time": "2022-10-25T04:45:11+00:00",
            "Rating": 53.0,
            "Duration": "08:00:00"
          }
        ]
      }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bderusha**
Issue Number: #131 

## Summary

Use System.CommandLine to support cleaner extensions and tests.
Refactor structure to better align to the core architecture.

## Changes

- Full implementation of #131 spec
- Uses `System.CommandLine` to support cleaner extensions and testing.
- Structured code to better mold to the consumer/aggregator/data-source tiered architecture
- Documentation for building and using the CLI
- i18n ready user messaging
- unit and integration tests

## Checklist

- [x] Local Tests Passing?
- [x] CICD and Pipeline Tests Passing?
- [x] Added any new Tests? Yes
- [x] Documentation Updates Made? Yes
- [x] Are there any API Changes? No
- [x] Are there breaking changes? Yes

## Is this a breaking change?
Yes, this changes the existing CLI contract.

## Anything else?

This PR Closes #131 
This PR Closes #168
This PR Closes #166

CC: @pritipath @vaughanknight @Willmish 

# Feature Demos

## Build the CLI

Use `dotnet build` to create the appropriate executable for your operating system, then navigate to the output directory to use your newly created executable.  By default the executable is `caw.exe` on Windows and `caw` on Mac/Linux, but this can be customized with additional build parameters if desired.

> NOTE: If no output directory is specified, the default path is `./src/CarbonAware.CLI/src/bin/<configuration>/<framework>/`

`dotnet build .\src\CarbonAware.CLI\src\CarbonAware.CLI.csproj -c Release -o <output dir>`

dotnet-build_help

## Emissions Commands

Use the `emissions` command to retrieve emissions data for various use-cases.

### Emissions by location and time

`--location` is a required parameter.
`--start-time` and `--end-time` are optional parameters.

`.\caw.exe emissions --location eastus --start-time 2022-09-01T12:45:11+00:00 --end-time 2022-09-02T12:45:11+00:00`
emissions

### Emissions for multiple locations

`.\caw.exe emissions --location eastus -location westus`
emissions-multiple-locations

### Best emissions for the given location and time period

Use the flag `--best` to get the optimal emissions for your specified location and time period.

`.\caw.exe emissions --location eastus --start-time 2022-09-01 --end-time 2022-09-03 --best`
emissions-best

### Average emissions for the given location and time period

Use the flag `--average` to calculate the average emissions for a location over time.

> NOTE: `--start-date` and `--end-date` are required with the `--average` flag.

`.\caw.exe emissions --location eastus --start-time 2022-09-01 --end-time 2022-09-03 --average`
emissions-average

## Forecast Commands

Use the `emissions-forecasts` command to get forecast data. The option `--requested-at` can be used to get a forecast which was generated in the past. If `--requested-at` is not specified, the current/most recent forecast is retrieved.

Additional options for `emissions-forecasts` include:
`--data-start-at`, which will filter out forecasted data points before the specified start at time.
`--data-end-at`, which will filter out forecasted data points after the specified end at time.
`--window-size,`, which represents the estimated duration (in minutes) of the workload being forecasted.

### Historical Forecast

`.\caw.exe emissions-forecasts --location eastus --data-start-at 2022-09-01T05:55:11Z --end-time 2022-09-01T07:55:11Z --requested-at 2022-09-01T05:50:11Z`
emissions-forecasts-historical

### Current Forecast

`.\caw.exe emissions-forecasts --location eastus --data-start-at <time within 24 hours of now> --end-time <time within 24 hours of now, but after --data-start-at>`
emissions-forecasts

### CODE REVIEW

**Comment by danuw** [comment]
Looks good - would also update the launchsetings.json under the project properties to have a valid launch command please. Will look further on Monday - hopefully we can get this one and the other one reviewed for Tuesday morning's meeting - Again happy to connect at some point on Monday to make sure I have not missed anything. (end of UK day for me is likely any time in the US afternoon for you)

@vaughanknight any comments ?

**Comment by esgraham** [comment]
This PR Closes #168 
This PR Closes #166

**Review by vaughanknight — APPROVED** [review]
Happy with these changes @bderusha ... likely will hold off on merge until this weekend (6th November) after the hackathon to avoid confusion for partiicpants working out of dev.

**Comment by vaughanknight** [comment]
NOTE -  Ready to merge, but NOT to be merged until 6th November.

**Pull request merged**
