### PR TITLE
Update published documentation to .NET 8

### LINKED ISSUE #506: Check our published documentation to identify any references to .NET7

### PR DESCRIPTION
**Pull request by nttDamien**
# Pull Request
Issue Number: #506 

## Summary
updating .NET refecences older than 8

## Changes
- also updated a broken link

## Checklist
- [NA ] Local Tests Passing?
- [ NA] CICD and Pipeline Tests Passing?
- [ NA] Added any new Tests?
- [x] Documentation Updates Made?
- [ NA] Are there any API Changes? If yes, please describe below.
- [ NA] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
No

## Is this a breaking change?
No

## Anything else?
Thanks to Sophie for all the prep work...

This PR Closes #506

### CODE REVIEW

**Comment by danuw** [comment]
Hi @nttDamien I think the only last 2 references I can find we could just rid are in those 2 links

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/4192933c6ad6fd36d21d29b5076bd9b785929c13/casdk-docs/docs/overview/enablement.md?plain=1#L591

replace `https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows#secret-manager` with `https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=windows#secret-manager`

and ...

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/4192933c6ad6fd36d21d29b5076bd9b785929c13/casdk-docs/docs/overview/enablement.md?plain=1#L601

replace `https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#default-application-configuration-sources` with 
> [default .NET configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?#default-application-configuration-sources`

I checked, it defaults to the latest GA version (so 8 at the mo) and I think we can leave it going forward...

Could you apply these 2 as well so I can merge please?

Thanks again for this already

**Comment by nttDamien** [comment]
> https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=windows#secret-manager

I checkd the files suggested by Sophie and for most no change was required. Although I doubt myself now that you found two places I missed ...

**Comment by danuw** [comment]
@nttDamien I checked everything for key terms and this was the last thing I could find just using 6.0... I think if we update these 2 things we should be good - (we are probably good without it too given you can change the version when you get to that page)
Lets discuss this morning

**Review by danuw — APPROVED** [review]
Great thanks @nttDamien

**Pull request merged**
