### PR TITLE
Keep packages/lib versions consistent across projects

### LINKED ISSUE #225: [Feature Contribution]: Keep packages/lib versions consistent across projects
### What happened?

Currently, the SDK refers to inconsistent versions of packages/libraries used. Ensure that all the projects use same versions of the libraries referenced in the SDK.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### PR DESCRIPTION
**Pull request by pritipath**
Issue Number: (#225)

## Summary
Ensure all projects reference same versions of libraries used

## Changes

- List of comprehensive changes

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
If yes, what are the expected API Changes? Please link to an API-Comparison workflow with the API Diff.

## Is this a breaking change?
If yes, what workflow does this break? 

## Anything else?
Other comments, collaborators, etc.
> Please follow [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to link Pull Requests to Issues via keywords

This PR Closes #225

### CODE REVIEW

**Comment by JenMadiedo** [comment]
Is there a plan within this work to ensure that this is always true automatically? Either through some code check, pipeline etc. so it's not just manually done?

**Review by bderusha — APPROVED** [review]

**Comment by bderusha** [comment]
> Is there a plan within this work to ensure that this is always true automatically? Either through some code check, pipeline etc. so it's not just manually done?

@pritipath  Check out [Directory.Build.targets](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022).  [This blog post ](https://codeopinion.com/nuget-packagereference-versions-solution-wide/) does a good job describing how to do this as well

**Comment by pritipath** [comment]
> Is there a plan within this work to ensure that this is always true automatically? Either through some code check, pipeline etc. so it's not just manually done?

Updated to have a centralized file that tracks the versions.

**Review by JenMadiedo — APPROVED** [review]
🚢 -it

**Review by juzuluag — APPROVED** [review]
👍

**Review by vaughanknight — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
