### PR TITLE
[Sample]: Jupyter notebook Demo of web API  

### PR DESCRIPTION
**Pull request by Willmish**
## Summary
Adds a jupyter notebook demo along with a setup guide for the environment. This an Example for the `/sample` directory, to showcase the usage of a deployed Carbon Aware Web API and a Python SDK generated with OpenAPI generator. The notebook goes through an example process of making Carbon Aware decisions around Cloud deployments, by showcasing benefits of time shifting and location shifting.

## Changes

- Adds new directory in the `samples` folder: `python-jupyter-notebook-webapi`.
- Adds a `README.md` file containing a short description of the demo along with a setup guide.
- Adds a `requirements.txt` file for the conda/python environment.
- Adds a `.env.template` file to be used as a template for a new `.env` file to provide URL for the deployed web API.
- Adds the Jupyter notebook `Carbon_aware_SDK_demo.ipynb` containing the described demo, with results stored.

## Checklist

- [x] Local Tests Passing?
- [x] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [x] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [x] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?
No.

## Is this a breaking change?
No.

### CODE REVIEW

**Comment by Willmish** [comment]
@danuw are you able to review/try it out ?

**Comment by vaughanknight** [comment]
This is currently blocked by #198

**Comment by vaughanknight** [comment]
@Willmish - is this still working current on the SDK?  Can you please test and happy to approve, just want to make sure it hasn't broken.

**Comment by Willmish** [comment]
Waiting until decision made regarding pip python packages being distributed for ca sdk api

**Comment by danuw** [comment]
I don't think you should wait - just pointing at doc on how to generate (which I believe you already had) from localhost is good enough for people to use. People could benefit from this already and this can always be updated when and if pip exist...

**Comment by Willmish** [comment]
Maybe host on google colab with python packages available at a public url

**Pull request closed without merging**
