### PR TITLE
Migrating Azure Functions sample to isolated worker model

### LINKED ISSUE #419: [Feature Contribution]: Migrate sample implementation of Azure Function to isolated worker model
### What happened?

Updating to .NET 8.0 (#404) is blocked by failing to run sample of Azure Function. It is implemented in in-process model which is not supported for .NET 8.0 now. (c.f. https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-august-2023-roadmap-update/ba-p/3910098 ) In addition to that, in-process model will be removed from .NET 9.0. So I think the sample should be migrated to isolated worker model.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### PR DESCRIPTION
**Pull request by tiwatsuka**
# Pull Request

Issue Number: #419 

## Summary

Azure Functions sample is now implemented with isolated worker model

## Changes

- Using `Program.cs` instead of `StartUp.cs`
- Change the base image of the container

## Checklist

- [x] Local Tests Passing?
- [x] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [x] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [x] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No.

## Is this a breaking change?

No.

This PR Closes #419

### CODE REVIEW

**Comment by Willmish** [comment]
This is to unblock https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404

**Comment by Willmish** [comment]
This is blocking for https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404 , this is moving to a different Azure Function model, see this comment. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404#issuecomment-1820487521 would be great if you can take a look @bderusha

**Comment by danuw** [comment]
@Willmish / @bderusha any updates please?

**Review by bderusha — APPROVED** [review]
These changes looks good to me.

**Comment by danuw** [comment]
Awesome. Thanks @bderusha (and thank you for not merging yet... :) )

**Comment by danuw** [comment]
moving to vnext as discussed

**Review by YaSuenag — APPROVED** [review]
LGTM

@vaughanknight @danuw Can you merge this?  
As @Willmish said, this is blocker of #404 .

**Pull request merged**
