### PR TITLE
Readme updates for clarity

### LINKED ISSUE #411: Update documentation for Project overview (ReadMe)
Overview of what the project is aiming to achieve and why
Explanation of how the project fits within [GSF theory of change ](https://greensoftware.foundation/articles/theory-of-change) 

README.md must also contain this banner at the top:

[!important] Incubation Project This project is an incubation project being run inside the Green Software Foundation; as such, we *DON’T recommend using it in any critical use case. Incubation projects are experimental, offer no support guarantee, have minimal governance and process, and may be retired at any moment. This project may one day graduate, in which case this disclaimer will be removed.

### PR DESCRIPTION
**Pull request by vaughanknight**
# Pull Request

Issue Number: #411 

## Summary

Updates to the readme file and some images.

## Changes

- Update to project readme file only
- Added some images 

## Checklist

- [x] Local Tests Passing?
- [x] CICD and Pipeline Tests Passing?
- [x] Documentation Updates Made?
- [x] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No

## Is this a breaking change?

No

## Anything else?

No

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR Closes #411

### CODE REVIEW

**Comment by vaughanknight** [comment]
@Sophietn - Are you able to help me source high quality version of 2 of the images please Sophie?

**Comment by vaughanknight** [comment]
image

These ones in the files directory need updating with better versions @Sophietn - I'm happy to push them to the repo if you can help me find them.

**Comment by vaughanknight** [comment]
I should add, I'm manually updating the 2nd image, it doesn't have the circling of carbon aware

**Comment by danuw** [comment]
LGTM, just waiting for the images @Sophietn may be able to help with.

**Comment by Sophietn** [comment]
Hi guys, I'll reach out to our designer to see if we have high quality ones on record, or can remake. Will update you here once I know

**Comment by Sophietn** [comment]
Hi @vaughanknight,
I've spoken with @Jenya-design. They're happy to help. Couple of clarifying questions:
- Where did you take those screenshots from? 
- Would you like any edits to the images?

**Comment by Jenya-design** [comment]
@vaughanknight @Sophietn 
Please check the images attached, they're 1920x1080, is it ok for you?

Carbom Aware SDK_demand shaping

Media Kit assets_infographic 3-11

**Comment by danuw** [comment]
Awesome.
@vaughanknight is this ready to do please? add the ready for review / tag me to let me know so I can merge this please

**Pull request merged**
