### PR TITLE
Docs fixes and release notes post for 1.6

### PR DESCRIPTION
**Pull request by danuw**
# Pull Request

Issue Number: (Link to Github Issue or Azure Dev Ops Task/Story)

## Summary

Fix for the release where docs workflow fails

## Changes

- List of comprehensive changes

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

If yes, what are the expected API Changes? Please link to an API-Comparison
workflow with the API Diff.

## Is this a breaking change?

If yes, what workflow does this break?

## Anything else?

Other comments, collaborators, etc.

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR Closes #<issue_number>

### CODE REVIEW

**Comment by danuw** [comment]
Workflow fails again.

FYI
My local uses 

```
node -v
v20.9.0
npm -v
10.8.2
```

and docusaurus is `3.4.0` (as it is telling me to update to 3.5.2)

**Comment by danuw** [comment]
we probably need to freeze the dependencies into a yarn lock which we dont yet have to see if that helps secure a steady set of dependencies for docusaurus to work seemlessly.

**Comment by tiwatsuka** [comment]
@danuw My apologies for the lack of clarity.  You also need to apply the change I made below.
https://github.com/tiwatsuka/carbon-aware-sdk/commit/8173906f8e1422b2c9417d9caef0f4c8c22b486e

**Comment by danuw** [comment]
Thank you very much I was creating a new test folder to get just that - thank you

**Comment by danuw** [comment]
@tiwatsuka / @YaSuenag could you review and approve please? and I hope do the same for the main branch too please?

**Review by YaSuenag — APPROVED** [review]

**Comment by danuw** [comment]
Thank you @YaSuenag

**Pull request merged**
