### PR TITLE
Readme updated links to images

### PR DESCRIPTION
**Pull request by danuw**
# Pull Request

Issue Number: (Link to Github Issue or Azure Dev Ops Task/Story)

## Summary

Readme updated links to images

## Changes

- Update links to both images on homepage

## Checklist

- [x] Local Tests Passing?
- [x] CICD and Pipeline Tests Passing?
- [x] Documentation Updates Made?
- [x] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

no

## Is this a breaking change?

NO

## Anything else?

Other comments, collaborators, etc.

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR Closes #<issue_number>

### CODE REVIEW

**Comment by danuw** [comment]
@vaughanknight @Willmish @Sophietn - should be a quick one

**Review by Willmish — APPROVED** [review]
checked the README, looks good now. thanks

**Review by Willmish — CHANGES_REQUESTED** [review]
Actually can you fix the other links while youre at it?

https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/470/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L42
I think its only this one thats left! ^

**Review by Sophietn — APPROVED** [review]
LGTM

**Comment by danuw** [comment]
@Willmish - done - thank you for flagging

**Review by Willmish — APPROVED** [review]
The fix pushed was still broken, Ive added the needed tweak. dont see anything else wrong with it so LGTM. please have a look at it too @danuw and verify you are happy with my changes :)

**Comment by danuw** [comment]
ok Thanks - yup I just tested the final result and it worked so will push through

**Pull request merged**
