### PR TITLE
Support location source setting in Helm chart

### PR DESCRIPTION
**Pull request by YaSuenag**
# Pull Request

## Summary

Add location source configuration to Helm chart

## Changes

- Add `locationSources` key to configure location source JSON.
- Ignore files which starts with `..` in `location-source` directory (Kubernetes sets real configuration file with `..`)
- Update documents for Helm

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [x] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No

## Is this a breaking change?

No

## Anything else?

I want to update Helm chart version and to publish new chart container if this PR is accepted.

### CODE REVIEW

**Comment by tiwatsuka** [comment]
@vaughanknight @danuw @YaSuenag 
I have validated this PR. The changes look good for me and it runs expectedly.

Configuration:
```
locationSources:
  enabled: enable
  files:
  - fileName: custom-locations-1.json
    locations: |-
      {
        "east": {
          "Latitude": "35.68",
          "Longitude": "139.77",
          "Name": "eastdc"
        },
        "west": {
          "Latitude": "34.6939",
          "Longitude": "135.5022",
          "Name": "westdc"
        }
      }
  - fileName: custom-locations-2.json
    locations: |-
      {
        "north": {
          "Latitude": "35.68",
          "Longitude": "139.77",
          "Name": "northdc"
        },
        "south": {
          "Latitude": "34.6939",
          "Longitude": "135.5022",
          "Name": "southdc"
        }
      }
```
After executing `helm install`:
```
$ kubectl describe configmap location-sources -n carbon-aware-sdk
Name:         location-sources
Namespace:    carbon-aware-sdk
Labels:       app.kubernetes.io/instance=casdk
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=carbon-aware-sdk
              app.kubernetes.io/version=v1.1.0
              helm.sh/chart=carbon-aware-sdk-1.0.0
Annotations:  meta.helm.sh/release-name: casdk
              meta.helm.sh/release-namespace: carbon-aware-sdk

Data
====
custom-locations-2.json:
----
{
  "north": {
    "Latitude": "35.68",
    "Longitude": "139.77",
    "Name": "northdc"
  },
  "south": {
    "Latitude": "34.6939",
    "Longitude": "135.5022",
    "Name": "southdc"
  }
}
custom-locations-1.json:
----
{
  "east": {
    "Latitude": "35.68",
    "Longitude": "139.77",
    "Name": "eastdc"
  },
  "west": {
    "Latitude": "34.6939",
    "Longitude": "135.5022",
    "Name": "westdc"
  }
}

BinaryData
====

Events:  <none>
```
```
$ kubectl get po -n carbon-aware-sdk -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP             NODE           NOMINATED NODE   READINESS GATES
webapi-6c8d49cf58-7h5bx   1/1     Running   0          7m55s   10.1.129.156   host-worker-1  <none>           <none>
$ curl http://10.1.129.156/locations 
{"east":{"latitude":35.68,"longitude":139.77,"name":"eastdc"},"west":{"latitude":34.6939,"longitude":135.5022,"name":"westdc"},"north":{"latitude":35.68,"longitude":139.77,"name":"northdc"},"south":{"latitude":34.6939,"longitude":135.5022,"name":"southdc"}}
```

**Review by tiwatsuka — APPROVED** [review]

**Comment by YaSuenag** [comment]
I set new version (1.1.0) for Helm chart in this PR.

As I wrote in #381 , Helm chart release can happen asynchronously with CASDK release. So I hope new Helm chart will be published after merging this PR - it means CASDK mainteiner kicks https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/.github/workflows/5-publish-helm-chart.yaml manually.

**Comment by danuw** [comment]
Thanks both and @tiwatsuka for the review and test confirmation

**Comment by YaSuenag** [comment]
Thank you for merging!

Could you kick [5-publish-helm-chart.yaml](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/.github/workflows/5-publish-helm-chart.yaml) to publish this chart?

**Comment by YaSuenag** [comment]
Helm chart v1.1.0 has been published: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pkgs/container/charts%2Fcarbon-aware-sdk/178053794?tag=1.1.0

Thanks a lot @danuw !

**Pull request merged**
