### PR TITLE
updated documentation to refer to the new arch diagram

### LINKED ISSUE #352: [Bug]: Documentation refers to old architecture diagram
### Contact Details

_No response_

### What happened?

The [overview.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/overview.md) file depicts old architecture diagram that shows Aggregators in the Business Tier.

With the new design, the Aggregator layer doesnt exist anymore and is replaced by the Handlers.  The overview.md file must be updated to refer to the new architecture diagram.

### client

WebAPI (Default)

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pritipath**
# Pull Request

Issue Number: #352 

## Summary

Updated documentation to refer to the new architecture diagram

## Changes

- List of comprehensive changes

## Checklist

- [ ] Local Tests Passing?
- [ ] CICD and Pipeline Tests Passing?
- [ ] Added any new Tests?
- [ ] Documentation Updates Made?
- [ ] Are there any API Changes? If yes, please describe below.
- [ ] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

If yes, what are the expected API Changes? Please link to an API-Comparison
workflow with the API Diff.

## Is this a breaking change?

If yes, what workflow does this break?

## Anything else?

Other comments, collaborators, etc.

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR Closes #352

### CODE REVIEW

**Review by juzuluag — APPROVED** [review]
👍

**Comment by pritipath** [comment]
@Willmish @vaughanknight  This is ready for GSF review

**Review by in4margaret — APPROVED** [review]

**Comment by Willmish** [comment]
Hi @pritipath  and thanks for adding the correct diagram! Regarding the DCO, if you could please fix this before it gets merged in, you have added a remediation for https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/353/commits/ec4270a559d1ac3624d068f8ae48925f68cfe3b2 but not for https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/353/commits/d9fdbe36c2a31c05a917cdc8817bdf5e4fe2474f - please see issue https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/309 for possible suggestions on how to fix this - for example Fabio's comment explains a nice method with git rebasing: https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/309#issuecomment-1472202540) OR SEE BELOW for suggested course of action.

Preferably you would also remove the 2 empty commits with incorrect DCO remediation. To do this:
1. `git reset --hard HEAD~2` will permanently REMOVE the last two commits from local repo OR `git reset --hard d9fdbe36c2a31c05a917cdc8817bdf5e4fe2474f` will do the same but reset exactly to this commit: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/353/commits/d9fdbe36c2a31c05a917cdc8817bdf5e4fe2474f , removing the empty incorrect remediation commit and the commit adding the single space.
2. NEXT, instead of `git commit --amend -s` you can add a correct remediation commit FOR BOTH unsigned commits, with :
```
git commit -m"DCO Remediation Commit for Priti <pritipathak@microsoft.com>

I, Priti <pritipathak@microsoft.com>, hereby add my Signed-off-by to this commit: ec4270a559d1ac3624d068f8ae48925f68cfe3b2
I, Priti <pritipathak@microsoft.com>, hereby add my Signed-off-by to this commit: d9fdbe36c2a31c05a917cdc8817bdf5e4fe2474f

Signed-off-by: Priti <pritipathak@microsoft.com>" --allow-empty
```
3. Finally, you can `git push -f` which will rewrite the upstream repo history on this branch.

Hopefully this is will help you out in fixing the issue!

**Review by Willmish — CHANGES_REQUESTED** [review]
diagram looks good, but please see DCO comment.

**Comment by pritipath** [comment]
> #363 - @pritipath resurfacing

@Willmish Fixed. Sorry for the delay, missed this somehow.

**Pull request closed without merging**
