### PR TITLE
Release 1.3 changelog

### LINKED ISSUE #474: Create release notes for 1.3
### What happened?

Create a PR with updated change log.

I will be using PRs listed here to start https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls?q=is%3Apr+label%3A1.3+is%3Aclosed

I will need support to ensure nothing was missed from the issues too... (start here - currently can only see one bug I will list too https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aissue+label%3A1.3+is%3Aclosed)

Please feel free to add anything missing in the comments...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

### PR DESCRIPTION
**Pull request by danuw**
# Pull Request

Issue Number: [(Link to Github Issue or Azure Dev Ops Task/Story)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/474)

## Summary

Release 1.3 changelog

## Changes

- Updated changelog for release 1.3

## Checklist

- [x] Local Tests Passing?
- [x] CICD and Pipeline Tests Passing?
- [x] Documentation Updates Made?
- [x] This is not a breaking change. If it is, please describe it below.

## Are there API Changes?

No

## Is this a breaking change?

No

## Anything else?

Other comments, collaborators, etc.

> Please follow
> [GitHub's suggested syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> to link Pull Requests to Issues via keywords

This PR Closes #474

### CODE REVIEW

**Comment by danuw** [comment]
I have used the following commands to help me create the release notes

```
gh pr list -R Green-Software-Foundation/carbon-aware-sdk --search "label:1.3 is:closed" --json number,title,url --template \
        '{{range .}}{{ printf "\n-[PR #%v" .number | autocolor "green"}} {{.title}} {{ printf "](%v)" .url}}{{end}}'

gh issue list -R Green-Software-Foundation/carbon-aware-sdk --search "label:1.3 is:closed" --json number,title,url --template \
        '{{range .}}{{ printf "\n-[#%v" .number | autocolor "green"}} {{.title}} {{ printf "](%v)" .url}}{{end}}'
```

This based on tags, but we could also use per date to match all changes such as using criteria like `closed:>=2024-01-17` such as 
```
gh pr list -R Green-Software-Foundation/carbon-aware-sdk --search "-label:agenda closed:>=2024-01-17" --json number,title,url --template \
        '{{range .}}{{ printf "\n-[PR #%v" .number | autocolor "green"}} {{.title}} {{ printf "](%v)" .url}}{{end}}'

gh issue list -R Green-Software-Foundation/carbon-aware-sdk --search "-label:agenda closed:>=2024-01-17" --json number,title,url --template \
        '{{range .}}{{ printf "\n-[#%v" .number | autocolor "green"}} {{.title}} {{ printf "](%v)" .url}}{{end}}'
```

which returns a more exhaustive list I may use more of:
-[PR #472 Update README.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/472)
-[PR #469 Update SECURITY.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/469)
-[PR #466 New documentation site with Docusaurus ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/466)
-[PR #464 Create SECURITY.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/464)
-[PR #463 Carbon hack 24 banner image fix ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/463)
-[PR #462 Docs/test coverage ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/462)
-[PR #461 CarbonHack24 Update to README.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/461)
-[PR #459 Readme updates for clarity ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/459)
-[PR #457 Features/codespaces quickstart ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/457)
-[PR #454 Update quickstart.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/454)
-[PR #453 Update overview.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/453)
-[PR #452 Update carbon-aware-cli.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/452)
-[PR #449 Support location source setting in Helm chart ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/449)
-[PR #442 Update containerization.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/442)
-[PR #441 Draft of enablement.md ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/441)
-[PR #432 Ignore - This is a test for copilot for PRs please ignore ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/432)
-[PR #431 Update documentation of Usefulness (adopters.md)  ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/431)
-[PR #430 Update WattTime registration link ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/430)
-[PR #359 Add 2b-generate-java-client.yaml ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/359)
-[#467 Update the Carbon Aware SDK docusaurus link ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/467)
-[#460 [Feature Contribution]: CarbonHack 24 banner added to readme to match IF and other GSF repos ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/460)
-[#438 [Bug]: Code coverage: Main release check issues to review ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/438)
-[#416 Add disclaimer banner to any public-facing documentation (docusaurus webpage) ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/416)
-[#415 Update documentation of secureness (security.md) ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/415)
-[#414 Update documentation of Usefulness (adopters.md) ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/414)
-[#413 Update documentation for Test Coverage ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/413)
-[#412 Update documentation for End User Guide (enablement.md) ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/412)
-[#411 Update documentation for Project overview (ReadMe) ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/411)
-[#382 [Bug]: Some GHA were failed due to empty workflow ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/382)
-[#344 [Bug]: Fix and update doc deployment workflow ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/344)
-[#260 [Feature Request]: Missing option to select WattTime model version (Auditability) ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/260)
-[#207 [Feature Contribution]: Enable codespaces for the SDK repo ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/207)%

**Comment by danuw** [comment]
FYI we can use this PR to remove the top banner and add the change log for 1.3 as a blog post

cc @vaughanknight @Sophietn @Willmish

**Comment by Sophietn** [comment]
Great thanks Dan. Rather than just removing the top banner we should change it to this copy from the [project lifecycle](https://oc.greensoftware.foundation/project-lifecycle.html#expectation-2):

[!important] Graduated Project This project is a Graduated Project, supported by the Green Software Foundation. The publicly available version documented in the README is trusted by the GSF. New versions of the project may be released, or it may move to the Maintained or Archived Stage.

**Comment by vaughanknight** [comment]
Happy to approve Dan and merge now, might be best to do the banner updates separate since it has different impacts?

**Pull request merged**
